language: java

jdk:
  - openjdk8

# Prevent "mvn install" default step
install: true

addons:
  sonarcloud:
    organization: "echebbi-github"
  apt:
    packages:
      # Required by XVFB
      - metacity

# Allow UI tests
dist: trusty

before_script:
  # Prepare the environment for UI tests
  - "export DISPLAY:99"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvbf some time to start
  - metacity --sm-disable --replace 2> metacity.err &
  # Fully clone repository to ease Sonar's analysis
  - git fetch --unshallow
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin
  # Prevent installed packages from being used during build
  - rm -rfv "$HOME/.m2/repository/fr/kazejiyu/ekumi/"

script: mvn verify -P jacoco sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Keep p2 information
cache:
   directories:
     - "$HOME/.m2/repository"
     - "$HOME/.sonar/cache"