language: java

addons:
  sonarcloud:
    organization: "echebbi-github"

# Prevents "mvn install" default step
install: true

# Allows UI tests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10 # give xvfb some time to start
  - git fetch --unshallow
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin
  # Prevent installed packages from being used during build
  - rm -rfv "$HOME/.m2/repository/fr/kazejiyu/ekumi/"

script: mvn clean verify -P jacoco sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Keep p2 information
cache:
   directories:
     - "$HOME/.m2/repository"